from django.shortcuts import render

from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, JsonResponse
import json
from datetime import datetime
from .models import VitalData
from rest_framework.viewsets import ModelViewSet
from vitaldata.serializers import VitalDataSerializer
from rest_framework.response import Response


def hello(request):
    return HttpResponse('欢迎使用Django！')


class VitalListView(View):
    '''
    列表视图
    '''

    def get(self, request):
        # 查询所有重点数据接口
        # vitaldata = VitalData.objects.all()
        print('test')
        vitaldata = VitalData.objects.all()
        # 遍历查询集合，取出里面每个书籍的模型对象，把模型转换成为字典
        serializer = VitalDataSerializer(instance=vitaldata, many=True)
        # vital_list = []
        # for vital in vitaldata:
        #     viatl_dict = {
        #         'id': vital.id,
        #         'tg_num': vital.tg_num,
        #         'tg_num_old': vital.tg_num_old,
        #         'tg_num_change': vital.tg_num_change,
        #         'tg_num_change_status': vital.tg_num_change_status,
        #         'meter_num': vital.meter_num,
        #         'meter_num_old': vital.meter_num_old,
        #         'meter_num_change': vital.meter_num_change,
        #         'meter_num_change_status': vital.meter_num_change_status,
        #         'new_tgs_num': vital.new_tgs_num,
        #         'new_tg_num_old': vital.new_tg_num_old,
        #         'new_tg_num_change': vital.new_tg_num_change,
        #         'new_tg_num_change_status': vital.new_tg_num_change_status,
        #         'nor_tgs_num': vital.nor_tgs_num,
        #         'nor_tgs_num_old': vital.nor_tgs_num_old,
        #         'nor_tgs_num_change': vital.nor_tgs_num_change,
        #         'nor_tgs_num_change_status': vital.nor_tgs_num_change_status,
        #         'abnor_tgs_num': vital.abnor_tgs_num,
        #         'abnor_tgs_num_old': vital.abnor_tgs_num_old,
        #         'abnor_tgs_num_change': vital.abnor_tgs_num_change,
        #         'abnor_tgs_num_change_status': vital.abnor_tgs_num_change_status,
        #         'tg_cal_rate': vital.tg_cal_rate,
        #         'tg_cal_rate_old': vital.tg_cal_rate_old,
        #         'tg_cal_rate_change': vital.tg_cal_rate_change,
        #         'tg_cal_rate_change_status': vital.tg_cal_rate_change_status,
        #         'obs_meters_num': vital.obs_meters_num,
        #         'obs_meters_num_old': vital.obs_meters_num_old,
        #         'obs_meters_num_change': vital.obs_meters_num_change,
        #         'obs_meters_num_change_status': vital.obs_meters_num_change_status,
        #         'nor_meters_num': vital.nor_meters_num,
        #         'nor_meters_num_old': vital.nor_meters_num_old,
        #         'nor_meters_num_change': vital.nor_meters_num_change,
        #         'nor_meters_num_change_status': vital.nor_meters_num_change_status,
        #         'abnor_meters_num': vital.abnor_meters_num,
        #         'abnor_meters_num_old': vital.abnor_meters_num_old,
        #         'abnor_meters_num_change': vital.abnor_meters_num_change,
        #         'abnor_meters_num_change_status': vital.abnor_meters_num_change_status,
        #         'meter_com_rate_num': vital.meter_com_rate_num,
        #         'meter_com_rate_num_old': vital.meter_com_rate_num_old,
        #         'meter_com_rate_num_change': vital.meter_com_rate_num_change,
        #         'meter_com_rate_num_change_status': vital.meter_com_rate_num_change_status,
        #         'un_govern_question_num': vital.un_govern_question_num,
        #         'un_govern_question_num_old': vital.un_govern_question_num_old,
        #         'un_govern_question_num_change': vital.un_govern_question_num_change,
        #         'un_govern_question_num_change_status': vital.un_govern_question_num_change_status,
        #         'cal_tgs_num': vital.cal_tgs_num,
        #         'cal_tgs_num_old': vital.cal_tgs_num_old,
        #         'cal_tgs_num_change': vital.cal_tgs_num_change,
        #         'cal_tgs_num_change_status': vital.cal_tgs_num_change_status,
        #         'un_govern_tgs_num': vital.un_govern_tgs_num,
        #         'un_govern_tgs_num_old': vital.un_govern_tgs_num_old,
        #         'un_govern_tgs_num_change': vital.un_govern_tgs_num_change,
        #         'un_govern_tgs_num_change_status': vital.un_govern_tgs_num_change_status,
        #         'involve_meters_num': vital.involve_meters_num,
        #         'involve_meters_num_old': vital.involve_meters_num_old,
        #         'involve_meters_num_change': vital.involve_meters_num_change,
        #         'involve_meters_num_change_status': vital.involve_meters_num_change_status,
        #         'white_tgs_num': vital.white_tgs_num,
        #         'white_tgs_num_old': vital.white_tgs_num_old,
        #         'white_tgs_num_change': vital.white_tgs_num_change,
        #         'white_tgs_num_change_status': vital.white_tgs_num_change_status,
        #         'all_abnor_tgs_num': vital.all_abnor_tgs_num,
        #         'all_abnor_tgs_num_old': vital.all_abnor_tgs_num_old,
        #         'all_abnor_tgs_num_change': vital.all_abnor_tgs_num_change,
        #         'all_abnor_tgs_num_change_status': vital.all_abnor_tgs_num_change_status,
        #         'abnor_tg_govern_rate_num': vital.abnor_tg_govern_rate_num,
        #         'abnor_tg_govern_rate_num_old': vital.abnor_tg_govern_rate_num_old,
        #         'abnor_tg_govern_rate_num_change': vital.abnor_tg_govern_rate_num_change,
        #         'abnor_tg_govern_rate_num_change_status': vital.abnor_tg_govern_rate_num_change_status,
        #         'all_questions_num': vital.all_questions_num,
        #         'all_questions_num_old': vital.all_questions_num_old,
        #         'all_questions_num_change': vital.all_questions_num_change,
        #         'all_questions_num_change_status': vital.all_questions_num_change_status,
        #         'questions_govern_rate': vital.questions_govern_rate,
        #         'questions_govern_rate_old': vital.questions_govern_rate_old,
        #         'questions_govern_rate_change': vital.questions_govern_rate_change,
        #         'questions_govern_rate_change_status': vital.questions_govern_rate_change_status,
        #         'precompute_time': vital.precompute_time,
        #         'precompute_time_old': vital.precompute_time_old,
        #         'precompute_time_change': vital.precompute_time_change,
        #         'precompute_time_change_status': vital.precompute_time_change_status,
        #         'check_meter_num_model': vital.check_meter_num_model,
        #         'check_meter_num_model_old': vital.check_meter_num_model_old,
        #         'check_meter_num_model_change': vital.check_meter_num_model_change,
        #         'check_meter_num_model_change_status': vital.check_meter_num_model_change_status,
        #         'check_meter_num_sz': vital.check_meter_num_sz,
        #         'check_meter_num_sz_old': vital.check_meter_num_sz_old,
        #         'check_meter_num_sz_change': vital.check_meter_num_sz_change,
        #         'check_meter_num_sz_change_status': vital.check_meter_num_sz_change_status,
        #         'container_version': vital.container_version,
        #         'container_version_old': vital.container_version_old,
        #         'cal_date': vital.cal_date,
        #         'cal_date_old': vital.cal_date_old,
        #     }
        #
        #     vital_list.append(viatl_dict)
            # 3. 响应，非字典类型需要设置safe=False
        # return JsonResponse(vital_list, safe=False)
        return Response(serializer.data)

    def post(self, request):
        """
        新增重点数据
        路由：POST /books/
        """
        json_bytes = request.body
        json_str = json_bytes.decode()
        vital_dict = json.loads(json_str)

        # 此处详细的校验参数省略

        vital = VitalData.objects.create(
            tg_num=vital_dict.get('tg_num'),
            tg_num_old=vital_dict.get('tg_num_old'),
            tg_num_change=vital_dict.get('tg_num_change'),
            tg_num_change_status=vital_dict.get('tg_num_change_status'),
            meter_num=vital_dict.get('meter_num'),
            meter_num_old=vital_dict.get('meter_num_old'),
            meter_num_change=vital_dict.get('meter_num_change'),
            meter_num_change_status=vital_dict.get('meter_num_change_status'),
            new_tgs_num=vital_dict.get('new_tgs_num'),
            new_tg_num_old=vital_dict.get('new_tg_num_old'),
            new_tg_num_change=vital_dict.get('new_tg_num_change'),
            new_tg_num_change_status=vital_dict.get('new_tg_num_change_status'),
            nor_tgs_num=vital_dict.get('nor_tgs_num'),
            nor_tgs_num_old=vital_dict.get('nor_tgs_num_old'),
            nor_tgs_num_change=vital_dict.get('nor_tgs_num_change'),
            nor_tgs_num_change_status=vital_dict.get('nor_tgs_num_change_status'),
            abnor_tgs_num=vital_dict.get('abnor_tgs_num'),
            abnor_tgs_num_old=vital_dict.get('abnor_tgs_num_old'),
            abnor_tgs_num_change=vital_dict.get('abnor_tgs_num_change'),
            abnor_tgs_num_change_status=vital_dict.get('abnor_tgs_num_change_status'),
            tg_cal_rate=vital_dict.get('tg_cal_rate'),
            tg_cal_rate_old=vital_dict.get('tg_cal_rate_old'),
            tg_cal_rate_change=vital_dict.get('tg_cal_rate_change'),
            tg_cal_rate_change_status=vital_dict.get('tg_cal_rate_change_status'),
            obs_meters_num=vital_dict.get('obs_meters_num'),
            obs_meters_num_old=vital_dict.get('obs_meters_num_old'),
            obs_meters_num_change=vital_dict.get('obs_meters_num_change'),
            obs_meters_num_change_status=vital_dict.get('obs_meters_num_change_status'),
            nor_meters_num=vital_dict.get('nor_meters_num'),
            nor_meters_num_old=vital_dict.get('nor_meters_num_old'),
            nor_meters_num_change=vital_dict.get('nor_meters_num_change'),
            nor_meters_num_change_status=vital_dict.get('nor_meters_num_change_status'),
            abnor_meters_num=vital_dict.get('abnor_meters_num'),
            abnor_meters_num_old=vital_dict.get('abnor_meters_num_old'),
            abnor_meters_nabnor_meters_num_changeum_old=vital_dict.get('abnor_meters_num_change'),
            abnor_meters_num_change_status=vital_dict.get('abnor_meters_num_change_status'),
            cal_tgs_num=vital_dict.get('cal_tgs_num'),
            cal_tgs_num_old=vital_dict.get('cal_tgs_num_old'),
            cal_tgs_num_change=vital_dict.get('cal_tgs_num_change'),
            cal_tgs_num_change_status=vital_dict.get('cal_tgs_num_change_status'),
            un_govern_tgs_num=vital_dict.get('un_govern_tgs_num'),
            un_govern_tgs_num_old=vital_dict.get('un_govern_tgs_num_old'),
            un_govern_tgs_num_change=vital_dict.get('un_govern_tgs_num_change'),
            un_govern_tgs_num_change_status=vital_dict.get('un_govern_tgs_num_change_status'),
            involve_meters_num=vital_dict.get('involve_meters_num'),
            involve_meters_num_old=vital_dict.get('involve_meters_num_old'),
            involve_meters_num_change=vital_dict.get('involve_meters_num_change'),
            involve_meters_num_change_status=vital_dict.get('involve_meters_num_change_status'),
            white_tgs_num=vital_dict.get('white_tgs_num'),
            white_tgs_num_old=vital_dict.get('white_tgs_num_old'),
            white_tgs_num_change=vital_dict.get('white_tgs_num_change'),
            white_tgs_num_change_status=vital_dict.get('white_tgs_num_change_status'),
            all_abnor_tgs_num=vital_dict.get('all_abnor_tgs_num'),
            all_abnor_tgs_num_old=vital_dict.get('all_abnor_tgs_num_old'),
            all_abnor_tgs_num_change=vital_dict.get('all_abnor_tgs_num_change'),
            all_abnor_tgs_num_change_status=vital_dict.get('all_abnor_tgs_num_change_status'),
            abnor_tg_govern_rate_num=vital_dict.get('abnor_tg_govern_rate_num'),
            abnor_tg_govern_rate_num_old=vital_dict.get('abnor_tg_govern_rate_num_old'),
            abnor_tg_govern_rate_num_change=vital_dict.get('abnor_tg_govern_rate_num_change'),
            abnor_tg_govern_rate_num_change_status=vital_dict.get('abnor_tg_govern_rate_num_change_status'),
            all_questions_num=vital_dict.get('all_questions_num'),
            all_questions_num_old=vital_dict.get('all_questions_num_old'),
            all_questions_num_change=vital_dict.get('all_questions_num_change'),
            all_questions_num_change_status=vital_dict.get('all_questions_num_change_status'),
            questions_govern_rate=vital_dict.get('questions_govern_rate'),
            questions_govern_rate_old=vital_dict.get('questions_govern_rate_old'),
            questions_govern_rate_change=vital_dict.get('questions_govern_rate_change'),
            questions_govern_rate_change_status=vital_dict.get('questions_govern_rate_change_status'),
            precompute_time=vital_dict.get('precompute_time'),
            precompute_time_old=vital_dict.get('precompute_time_old'),
            precompute_time_change=vital_dict.get('precompute_time_change'),
            precompute_time_change_status=vital_dict.get('precompute_time_change_status'),
            over_meters=vital_dict.get('over_meters'),
            over_meters_old=vital_dict.get('over_meters_old'),
            over_meters_change=vital_dict.get('over_meters_change'),
            over_meters_change_status=vital_dict.get('over_meters_change_status'),
            check_meter_num_model=vital_dict.get('check_meter_num_model'),
            check_meter_num_model_old=vital_dict.get('check_meter_num_model_old'),
            check_meter_num_model_change=vital_dict.get('check_meter_num_model_change'),
            check_meter_num_model_change_status=vital_dict.get('check_meter_num_model_change_status'),
            check_meter_num_sz=vital_dict.get('check_meter_num_sz'),
            check_meter_num_sz_old=vital_dict.get('check_meter_num_sz_old'),
            check_meter_num_sz_change=vital_dict.get('check_meter_num_sz_change'),
            check_meter_num_sz_change_status=vital_dict.get('check_meter_num_sz_change_status'),
            meter_com_rate_num=vital_dict.get('meter_com_rate_num'),
            meter_com_rate_num_old=vital_dict.get('meter_com_rate_num_old'),
            meter_com_rate_num_change=vital_dict.get('meter_com_rate_num_change'),
            meter_com_rate_num_change_status=vital_dict.get('meter_com_rate_num_change_status'),
            un_govern_question_num=vital_dict.get('un_govern_question_num'),
            un_govern_question_num_old=vital_dict.get('un_govern_question_num_old'),
            un_govern_question_num_change=vital_dict.get('un_govern_question_num_change'),
            un_govern_question_num_change_status=vital_dict.get('un_govern_question_num_change_status'),
            container_version=vital_dict.get('container_version'),
            container_version_old=vital_dict.get('container_version_old'),
            cal_date=datetime.strptime(vital_dict.get('cal_date'), '%Y-%m-%d').date(),
            cal_date_old=datetime.strptime(vital_dict.get('cal_date_old'), '%Y-%m-%d').date(),
        )

        return JsonResponse({
            'id': vital.id,
            'tg_num': vital.tg_num,
            'tg_num_old': vital.tg_num_old,
            'tg_num_change': vital.tg_num_change,
            'tg_num_change_status': vital.tg_num_change_status,
            'meter_num': vital.meter_num,
            'meter_num_old': vital.meter_num_old,
            'meter_num_change': vital.meter_num_change,
            'meter_num_change_status': vital.meter_num_change_status,
            'new_tgs_num': vital.new_tgs_num,
            'new_tg_num_old': vital.new_tg_num_old,
            'new_tg_num_change': vital.new_tg_num_change,
            'new_tg_num_change_status': vital.new_tg_num_change_status,
            'nor_tgs_num': vital.nor_tgs_num,
            'nor_tgs_num_old': vital.nor_tgs_num_old,
            'nor_tgs_num_change': vital.nor_tgs_num_change,
            'nor_tgs_num_change_status': vital.nor_tgs_num_change_status,
            'abnor_tgs_num': vital.abnor_tgs_num,
            'abnor_tgs_num_old': vital.abnor_tgs_num_old,
            'abnor_tgs_num_change': vital.abnor_tgs_num_change,
            'abnor_tgs_num_change_status': vital.abnor_tgs_num_change_status,
            'tg_cal_rate': vital.tg_cal_rate,
            'tg_cal_rate_old': vital.tg_cal_rate_old,
            'tg_cal_rate_change': vital.tg_cal_rate_change,
            'tg_cal_rate_change_status': vital.tg_cal_rate_change_status,
            'obs_meters_num': vital.obs_meters_num,
            'obs_meters_num_old': vital.obs_meters_num_old,
            'obs_meters_num_change': vital.obs_meters_num_change,
            'obs_meters_num_change_status': vital.obs_meters_num_change_status,
            'nor_meters_num': vital.nor_meters_num,
            'nor_meters_num_old': vital.nor_meters_num_old,
            'nor_meters_num_change': vital.nor_meters_num_change,
            'nor_meters_num_change_status': vital.nor_meters_num_change_status,
            'abnor_meters_num': vital.abnor_meters_num,
            'abnor_meters_num_old': vital.abnor_meters_num_old,
            'abnor_meters_num_change': vital.abnor_meters_num_change,
            'abnor_meters_num_change_status': vital.abnor_meters_num_change_status,
            'meter_com_rate_num': vital.meter_com_rate_num,
            'meter_com_rate_num_old': vital.meter_com_rate_num_old,
            'meter_com_rate_num_change': vital.meter_com_rate_num_change,
            'meter_com_rate_num_change_status': vital.meter_com_rate_num_change_status,
            'un_govern_question_num': vital.un_govern_question_num,
            'un_govern_question_num_old': vital.un_govern_question_num_old,
            'un_govern_question_num_change': vital.un_govern_question_num_change,
            'un_govern_question_num_change_status': vital.un_govern_question_num_change_status,
            'cal_tgs_num': vital.cal_tgs_num,
            'cal_tgs_num_old': vital.cal_tgs_num_old,
            'cal_tgs_num_change': vital.cal_tgs_num_change,
            'cal_tgs_num_change_status': vital.cal_tgs_num_change_status,
            'un_govern_tgs_num': vital.un_govern_tgs_num,
            'un_govern_tgs_num_old': vital.un_govern_tgs_num_old,
            'un_govern_tgs_num_change': vital.un_govern_tgs_num_change,
            'un_govern_tgs_num_change_status': vital.un_govern_tgs_num_change_status,
            'involve_meters_num': vital.involve_meters_num,
            'involve_meters_num_old': vital.involve_meters_num_old,
            'involve_meters_num_change': vital.involve_meters_num_change,
            'involve_meters_num_change_status': vital.involve_meters_num_change_status,
            'white_tgs_num': vital.white_tgs_num,
            'white_tgs_num_old': vital.white_tgs_num_old,
            'white_tgs_num_change': vital.white_tgs_num_change,
            'white_tgs_num_change_status': vital.white_tgs_num_change_status,
            'all_abnor_tgs_num': vital.all_abnor_tgs_num,
            'all_abnor_tgs_num_old': vital.all_abnor_tgs_num_old,
            'all_abnor_tgs_num_change': vital.all_abnor_tgs_num_change,
            'all_abnor_tgs_num_change_status': vital.all_abnor_tgs_num_change_status,
            'abnor_tg_govern_rate_num': vital.abnor_tg_govern_rate_num,
            'abnor_tg_govern_rate_num_old': vital.abnor_tg_govern_rate_num_old,
            'abnor_tg_govern_rate_num_change': vital.abnor_tg_govern_rate_num_change,
            'abnor_tg_govern_rate_num_change_status': vital.abnor_tg_govern_rate_num_change_status,
            'all_questions_num': vital.all_questions_num,
            'all_questions_num_old': vital.all_questions_num_old,
            'all_questions_num_change': vital.all_questions_num_change,
            'all_questions_num_change_status': vital.all_questions_num_change_status,
            'questions_govern_rate': vital.questions_govern_rate,
            'questions_govern_rate_old': vital.questions_govern_rate_old,
            'questions_govern_rate_change': vital.questions_govern_rate_change,
            'questions_govern_rate_change_status': vital.questions_govern_rate_change_status,
            'precompute_time': vital.precompute_time,
            'precompute_time_old': vital.precompute_time_old,
            'precompute_time_change': vital.precompute_time_change,
            'precompute_time_change_status': vital.precompute_time_change_status,
            'over_meters': vital.over_meters,
            'over_meters_old': vital.over_meters_old,
            'over_meters_change': vital.over_meters_change,
            'over_meters_change_status': vital.over_meters_change_status,
            'check_meter_num_model': vital.check_meter_num_model,
            'check_meter_num_model_old': vital.check_meter_num_model_old,
            'check_meter_num_model_change': vital.check_meter_num_model_change,
            'check_meter_num_model_change_status': vital.check_meter_num_model_change_status,
            'check_meter_num_sz': vital.check_meter_num_sz,
            'check_meter_num_sz_old': vital.check_meter_num_sz_old,
            'check_meter_num_sz_change': vital.check_meter_num_sz_change,
            'check_meter_num_sz_change_status': vital.check_meter_num_sz_change_status,
            'container_version': vital.container_version,
            'container_version_old': vital.container_version_old,
            'cal_date': vital.cal_date,
            'cal_date_old': vital.cal_date_old,

        }, status=201)


class DetailView(View):
    '''
    详情视图
    '''

    def get(self, request, pk):
        # 查询指定图书接口
        # 1、获取出指定pk的那个模型对象
        try:
            vital = VitalData.objects.get(cal_date=pk)
        except VitalData.DoesNotExist:
            return HttpResponse({'message': '查询的数据不存在'}, status=404)

        # 2、模型对象转字典
        viatl_dict = {
            'id': vital.id,
            'tg_num': vital.tg_num,
            'tg_num_old': vital.tg_num_old,
            'tg_num_change': vital.tg_num_change,
            'tg_num_change_status': vital.tg_num_change_status,
            'meter_num': vital.meter_num,
            'meter_num_old': vital.meter_num_old,
            'meter_num_change': vital.meter_num_change,
            'meter_num_change_status': vital.meter_num_change_status,
            'new_tgs_num': vital.new_tgs_num,
            'new_tg_num_old': vital.new_tg_num_old,
            'new_tg_num_change': vital.new_tg_num_change,
            'new_tg_num_change_status': vital.new_tg_num_change_status,
            'nor_tgs_num': vital.nor_tgs_num,
            'nor_tgs_num_old': vital.nor_tgs_num_old,
            'nor_tgs_num_change': vital.nor_tgs_num_change,
            'nor_tgs_num_change_status': vital.nor_tgs_num_change_status,
            'abnor_tgs_num': vital.abnor_tgs_num,
            'abnor_tgs_num_old': vital.abnor_tgs_num_old,
            'abnor_tgs_num_change': vital.abnor_tgs_num_change,
            'abnor_tgs_num_change_status': vital.abnor_tgs_num_change_status,
            'tg_cal_rate': vital.tg_cal_rate,
            'tg_cal_rate_old': vital.tg_cal_rate_old,
            'tg_cal_rate_change': vital.tg_cal_rate_change,
            'tg_cal_rate_change_status': vital.tg_cal_rate_change_status,
            'obs_meters_num': vital.obs_meters_num,
            'obs_meters_num_old': vital.obs_meters_num_old,
            'obs_meters_num_change': vital.obs_meters_num_change,
            'obs_meters_num_change_status': vital.obs_meters_num_change_status,
            'nor_meters_num': vital.nor_meters_num,
            'nor_meters_num_old': vital.nor_meters_num_old,
            'nor_meters_num_change': vital.nor_meters_num_change,
            'nor_meters_num_change_status': vital.nor_meters_num_change_status,
            'abnor_meters_num': vital.abnor_meters_num,
            'abnor_meters_num_old': vital.abnor_meters_num_old,
            'abnor_meters_num_change': vital.abnor_meters_num_change,
            'abnor_meters_num_change_status': vital.abnor_meters_num_change_status,
            'meter_com_rate_num': vital.meter_com_rate_num,
            'meter_com_rate_num_old': vital.meter_com_rate_num_old,
            'meter_com_rate_num_change': vital.meter_com_rate_num_change,
            'meter_com_rate_num_change_status': vital.meter_com_rate_num_change_status,
            'un_govern_question_num': vital.un_govern_question_num,
            'un_govern_question_num_old': vital.un_govern_question_num_old,
            'un_govern_question_num_change': vital.un_govern_question_num_change,
            'un_govern_question_num_change_status': vital.un_govern_question_num_change_status,
            'cal_tgs_num': vital.cal_tgs_num,
            'cal_tgs_num_old': vital.cal_tgs_num_old,
            'cal_tgs_num_change': vital.cal_tgs_num_change,
            'cal_tgs_num_change_status': vital.cal_tgs_num_change_status,
            'un_govern_tgs_num': vital.un_govern_tgs_num,
            'un_govern_tgs_num_old': vital.un_govern_tgs_num_old,
            'un_govern_tgs_num_change': vital.un_govern_tgs_num_change,
            'un_govern_tgs_num_change_status': vital.un_govern_tgs_num_change_status,
            'involve_meters_num': vital.involve_meters_num,
            'involve_meters_num_old': vital.involve_meters_num_old,
            'involve_meters_num_change': vital.involve_meters_num_change,
            'involve_meters_num_change_status': vital.involve_meters_num_change_status,
            'white_tgs_num': vital.white_tgs_num,
            'white_tgs_num_old': vital.white_tgs_num_old,
            'white_tgs_num_change': vital.white_tgs_num_change,
            'white_tgs_num_change_status': vital.white_tgs_num_change_status,
            'all_abnor_tgs_num': vital.all_abnor_tgs_num,
            'all_abnor_tgs_num_old': vital.all_abnor_tgs_num_old,
            'all_abnor_tgs_num_change': vital.all_abnor_tgs_num_change,
            'all_abnor_tgs_num_change_status': vital.all_abnor_tgs_num_change_status,
            'abnor_tg_govern_rate_num': vital.abnor_tg_govern_rate_num,
            'abnor_tg_govern_rate_num_old': vital.abnor_tg_govern_rate_num_old,
            'abnor_tg_govern_rate_num_change': vital.abnor_tg_govern_rate_num_change,
            'abnor_tg_govern_rate_num_change_status': vital.abnor_tg_govern_rate_num_change_status,
            'all_questions_num': vital.all_questions_num,
            'all_questions_num_old': vital.all_questions_num_old,
            'all_questions_num_change': vital.all_questions_num_change,
            'all_questions_num_change_status': vital.all_questions_num_change_status,
            'questions_govern_rate': vital.questions_govern_rate,
            'questions_govern_rate_old': vital.questions_govern_rate_old,
            'questions_govern_rate_change': vital.questions_govern_rate_change,
            'questions_govern_rate_change_status': vital.questions_govern_rate_change_status,
            'precompute_time': vital.precompute_time,
            'precompute_time_old': vital.precompute_time_old,
            'precompute_time_change': vital.precompute_time_change,
            'precompute_time_change_status': vital.precompute_time_change_status,
            'over_meters': vital.over_meters,
            'over_meters_old': vital.over_meters_old,
            'over_meters_change': vital.over_meters_change,
            'over_meters_change_status': vital.over_meters_change_status,
            'check_meter_num_model': vital.check_meter_num_model,
            'check_meter_num_model_old': vital.check_meter_num_model_old,
            'check_meter_num_model_change': vital.check_meter_num_model_change,
            'check_meter_num_model_change_status': vital.check_meter_num_model_change_status,
            'check_meter_num_sz': vital.check_meter_num_sz,
            'check_meter_num_sz_old': vital.check_meter_num_sz_old,
            'check_meter_num_sz_change': vital.check_meter_num_sz_change,
            'check_meter_num_sz_change_status': vital.check_meter_num_sz_change_status,
            'container_version': vital.container_version,
            'container_version_old': vital.container_version_old,
            'cal_date': vital.cal_date,
            'cal_date_old': vital.cal_date_old,
        }
        # 3、响应
        return JsonResponse(viatl_dict)

    def put(self, request, pk):
        """
        修改图书信息
        路由： PUT  /books/<pk>
        """
        try:
            vital = VitalData.objects.get(pk=pk)
            print(vital.id)
        except VitalData.DoesNotExist:
            return HttpResponse(status=404)

        json_bytes = request.body
        json_str = json_bytes.decode()
        vital_dict = json.loads(json_str)
        # 此处详细的校验参数省略

        vital.tg_num = vital_dict.get('tg_num')
        vital.tg_num_old = vital_dict.get('tg_num_old')
        vital.tg_num_change = vital_dict.get('tg_num_change')
        vital.tg_num_change_status = vital_dict.get('tg_num_change_status')
        vital.tg_num = vital_dict.get('tg_num')
        meter_num = vital_dict.get('meter_num'),
        meter_num_old = vital_dict.get('meter_num_old'),
        meter_num_change = vital_dict.get('meter_num_change'),
        meter_num_change_status = vital_dict.get('meter_num_change_status'),
        new_tgs_num = vital_dict.get('new_tgs_num'),
        new_tg_num_old = vital_dict.get('new_tg_num_old'),
        new_tg_num_change = vital_dict.get('new_tg_num_change'),
        new_tg_num_change_status = vital_dict.get('new_tg_num_change_status'),
        nor_tgs_num = vital_dict.get('nor_tgs_num'),
        nor_tgs_num_old = vital_dict.get('nor_tgs_num_old'),
        nor_tgs_num_change = vital_dict.get('nor_tgs_num_change'),
        nor_tgs_num_change_status = vital_dict.get('nor_tgs_num_change_status'),
        abnor_tgs_num = vital_dict.get('abnor_tgs_num'),
        abnor_tgs_num_old = vital_dict.get('abnor_tgs_num_old'),
        abnor_tgs_num_change = vital_dict.get('abnor_tgs_num_change'),
        abnor_tgs_num_change_status = vital_dict.get('abnor_tgs_num_change_status'),
        tg_cal_rate = vital_dict.get('tg_cal_rate'),
        tg_cal_rate_old = vital_dict.get('tg_cal_rate_old'),
        tg_cal_rate_change = vital_dict.get('tg_cal_rate_change'),
        tg_cal_rate_change_status = vital_dict.get('tg_cal_rate_change_status'),
        obs_meters_num = vital_dict.get('obs_meters_num'),
        obs_meters_num_old = vital_dict.get('obs_meters_num_old'),
        obs_meters_num_change = vital_dict.get('obs_meters_num_change'),
        obs_meters_num_change_status = vital_dict.get('obs_meters_num_change_status'),
        nor_meters_num = vital_dict.get('nor_meters_num'),
        nor_meters_num_old = vital_dict.get('nor_meters_num_old'),
        nor_meters_num_change = vital_dict.get('nor_meters_num_change'),
        nor_meters_num_change_status = vital_dict.get('nor_meters_num_change_status'),
        abnor_meters_num = vital_dict.get('abnor_meters_num'),
        abnor_meters_num_old = vital_dict.get('abnor_meters_num_old'),
        abnor_meters_nabnor_meters_num_changeum_old = vital_dict.get('abnor_meters_num_change'),
        abnor_meters_num_change_status = vital_dict.get('abnor_meters_num_change_status'),
        cal_tgs_num = vital_dict.get('cal_tgs_num'),
        cal_tgs_num_old = vital_dict.get('cal_tgs_num_old'),
        cal_tgs_num_change = vital_dict.get('cal_tgs_num_change'),
        cal_tgs_num_change_status = vital_dict.get('cal_tgs_num_change_status'),
        un_govern_tgs_num = vital_dict.get('un_govern_tgs_num'),
        un_govern_tgs_num_old = vital_dict.get('un_govern_tgs_num_old'),
        un_govern_tgs_num_change = vital_dict.get('un_govern_tgs_num_change'),
        un_govern_tgs_num_change_status = vital_dict.get('un_govern_tgs_num_change_status'),
        involve_meters_num = vital_dict.get('involve_meters_num'),
        involve_meters_num_old = vital_dict.get('involve_meters_num_old'),
        involve_meters_num_change = vital_dict.get('involve_meters_num_change'),
        involve_meters_num_change_status = vital_dict.get('involve_meters_num_change_status'),
        white_tgs_num = vital_dict.get('white_tgs_num'),
        white_tgs_num_old = vital_dict.get('white_tgs_num_old'),
        white_tgs_num_change = vital_dict.get('white_tgs_num_change'),
        white_tgs_num_change_status = vital_dict.get('white_tgs_num_change_status'),
        all_abnor_tgs_num = vital_dict.get('all_abnor_tgs_num'),
        all_abnor_tgs_num_old = vital_dict.get('all_abnor_tgs_num_old'),
        all_abnor_tgs_num_change = vital_dict.get('all_abnor_tgs_num_change'),
        all_abnor_tgs_num_change_status = vital_dict.get('all_abnor_tgs_num_change_status'),
        abnor_tg_govern_rate_num = vital_dict.get('abnor_tg_govern_rate_num'),
        abnor_tg_govern_rate_num_old = vital_dict.get('abnor_tg_govern_rate_num_old'),
        abnor_tg_govern_rate_num_change = vital_dict.get('abnor_tg_govern_rate_num_change'),
        abnor_tg_govern_rate_num_change_status = vital_dict.get('abnor_tg_govern_rate_num_change_status'),
        all_questions_num = vital_dict.get('all_questions_num'),
        all_questions_num_old = vital_dict.get('all_questions_num_old'),
        all_questions_num_change = vital_dict.get('all_questions_num_change'),
        all_questions_num_change_status = vital_dict.get('all_questions_num_change_status'),
        questions_govern_rate = vital_dict.get('questions_govern_rate'),
        questions_govern_rate_old = vital_dict.get('questions_govern_rate_old'),
        questions_govern_rate_change = vital_dict.get('questions_govern_rate_change'),
        questions_govern_rate_change_status = vital_dict.get('questions_govern_rate_change_status'),
        precompute_time = vital_dict.get('precompute_time'),
        precompute_time_old = vital_dict.get('precompute_time_old'),
        precompute_time_change = vital_dict.get('precompute_time_change'),
        precompute_time_change_status = vital_dict.get('precompute_time_change_status'),
        over_meters = vital_dict.get('over_meters'),
        over_meters_old = vital_dict.get('over_meters_old'),
        over_meters_change = vital_dict.get('over_meters_change'),
        over_meters_change_status = vital_dict.get('over_meters_change_status'),
        check_meter_num_model = vital_dict.get('check_meter_num_model'),
        check_meter_num_model_old = vital_dict.get('check_meter_num_model_old'),
        check_meter_num_model_change = vital_dict.get('check_meter_num_model_change'),
        check_meter_num_model_change_status = vital_dict.get('check_meter_num_model_change_status'),
        check_meter_num_sz = vital_dict.get('check_meter_num_sz'),
        check_meter_num_sz_old = vital_dict.get('check_meter_num_sz_old'),
        check_meter_num_sz_change = vital_dict.get('check_meter_num_sz_change'),
        check_meter_num_sz_change_status = vital_dict.get('check_meter_num_sz_change_status'),
        meter_com_rate_num = vital_dict.get('meter_com_rate_num'),
        meter_com_rate_num_old = vital_dict.get('meter_com_rate_num_old'),
        meter_com_rate_num_change = vital_dict.get('meter_com_rate_num_change'),
        meter_com_rate_num_change_status = vital_dict.get('meter_com_rate_num_change_status'),
        un_govern_question_num = vital_dict.get('un_govern_question_num'),
        un_govern_question_num_old = vital_dict.get('un_govern_question_num_old'),
        un_govern_question_num_change = vital_dict.get('un_govern_question_num_change'),
        un_govern_question_num_change_status = vital_dict.get('un_govern_question_num_change_status'),
        container_version = vital_dict.get('container_version'),
        container_version_old = vital_dict.get('container_version_old'),
        cal_date = datetime.strptime(vital_dict.get('cal_date'), '%Y-%m-%d').date(),
        cal_date_old = datetime.strptime(vital_dict.get('cal_date_old'), '%Y-%m-%d').date(),
        vital.save()

        return JsonResponse({
            'id': vital.id,
            'tg_num': vital.tg_num,
            'tg_num_old': vital.tg_num_old,
            'tg_num_change': vital.tg_num_change,
            'tg_num_change_status': vital.tg_num_change_status,
            'meter_num': vital.meter_num,
            'meter_num_old': vital.meter_num_old,
            'meter_num_change': vital.meter_num_change,
            'meter_num_change_status': vital.meter_num_change_status,
            'new_tgs_num': vital.new_tgs_num,
            'new_tg_num_old': vital.new_tg_num_old,
            'new_tg_num_change': vital.new_tg_num_change,
            'new_tg_num_change_status': vital.new_tg_num_change_status,
            'nor_tgs_num': vital.nor_tgs_num,
            'nor_tgs_num_old': vital.nor_tgs_num_old,
            'nor_tgs_num_change': vital.nor_tgs_num_change,
            'nor_tgs_num_change_status': vital.nor_tgs_num_change_status,
            'abnor_tgs_num': vital.abnor_tgs_num,
            'abnor_tgs_num_old': vital.abnor_tgs_num_old,
            'abnor_tgs_num_change': vital.abnor_tgs_num_change,
            'abnor_tgs_num_change_status': vital.abnor_tgs_num_change_status,
            'tg_cal_rate': vital.tg_cal_rate,
            'tg_cal_rate_old': vital.tg_cal_rate_old,
            'tg_cal_rate_change': vital.tg_cal_rate_change,
            'tg_cal_rate_change_status': vital.tg_cal_rate_change_status,
            'obs_meters_num': vital.obs_meters_num,
            'obs_meters_num_old': vital.obs_meters_num_old,
            'obs_meters_num_change': vital.obs_meters_num_change,
            'obs_meters_num_change_status': vital.obs_meters_num_change_status,
            'nor_meters_num': vital.nor_meters_num,
            'nor_meters_num_old': vital.nor_meters_num_old,
            'nor_meters_num_change': vital.nor_meters_num_change,
            'nor_meters_num_change_status': vital.nor_meters_num_change_status,
            'abnor_meters_num': vital.abnor_meters_num,
            'abnor_meters_num_old': vital.abnor_meters_num_old,
            'abnor_meters_num_change': vital.abnor_meters_num_change,
            'abnor_meters_num_change_status': vital.abnor_meters_num_change_status,
            'meter_com_rate_num': vital.meter_com_rate_num,
            'meter_com_rate_num_old': vital.meter_com_rate_num_old,
            'meter_com_rate_num_change': vital.meter_com_rate_num_change,
            'meter_com_rate_num_change_status': vital.meter_com_rate_num_change_status,
            'un_govern_question_num': vital.un_govern_question_num,
            'un_govern_question_num_old': vital.un_govern_question_num_old,
            'un_govern_question_num_change': vital.un_govern_question_num_change,
            'un_govern_question_num_change_status': vital.un_govern_question_num_change_status,
            'cal_tgs_num': vital.cal_tgs_num,
            'cal_tgs_num_old': vital.cal_tgs_num_old,
            'cal_tgs_num_change': vital.cal_tgs_num_change,
            'cal_tgs_num_change_status': vital.cal_tgs_num_change_status,
            'un_govern_tgs_num': vital.un_govern_tgs_num,
            'un_govern_tgs_num_old': vital.un_govern_tgs_num_old,
            'un_govern_tgs_num_change': vital.un_govern_tgs_num_change,
            'un_govern_tgs_num_change_status': vital.un_govern_tgs_num_change_status,
            'involve_meters_num': vital.involve_meters_num,
            'involve_meters_num_old': vital.involve_meters_num_old,
            'involve_meters_num_change': vital.involve_meters_num_change,
            'involve_meters_num_change_status': vital.involve_meters_num_change_status,
            'white_tgs_num': vital.white_tgs_num,
            'white_tgs_num_old': vital.white_tgs_num_old,
            'white_tgs_num_change': vital.white_tgs_num_change,
            'white_tgs_num_change_status': vital.white_tgs_num_change_status,
            'all_abnor_tgs_num': vital.all_abnor_tgs_num,
            'all_abnor_tgs_num_old': vital.all_abnor_tgs_num_old,
            'all_abnor_tgs_num_change': vital.all_abnor_tgs_num_change,
            'all_abnor_tgs_num_change_status': vital.all_abnor_tgs_num_change_status,
            'abnor_tg_govern_rate_num': vital.abnor_tg_govern_rate_num,
            'abnor_tg_govern_rate_num_old': vital.abnor_tg_govern_rate_num_old,
            'abnor_tg_govern_rate_num_change': vital.abnor_tg_govern_rate_num_change,
            'abnor_tg_govern_rate_num_change_status': vital.abnor_tg_govern_rate_num_change_status,
            'all_questions_num': vital.all_questions_num,
            'all_questions_num_old': vital.all_questions_num_old,
            'all_questions_num_change': vital.all_questions_num_change,
            'all_questions_num_change_status': vital.all_questions_num_change_status,
            'questions_govern_rate': vital.questions_govern_rate,
            'questions_govern_rate_old': vital.questions_govern_rate_old,
            'questions_govern_rate_change': vital.questions_govern_rate_change,
            'questions_govern_rate_change_status': vital.questions_govern_rate_change_status,
            'precompute_time': vital.precompute_time,
            'precompute_time_old': vital.precompute_time_old,
            'precompute_time_change': vital.precompute_time_change,
            'precompute_time_change_status': vital.precompute_time_change_status,
            'over_meters': vital.over_meters,
            'over_meters_old': vital.over_meters_old,
            'over_meters_change': vital.over_meters_change,
            'over_meters_change_status': vital.over_meters_change_status,
            'check_meter_num_model': vital.check_meter_num_model,
            'check_meter_num_model_old': vital.check_meter_num_model_old,
            'check_meter_num_model_change': vital.check_meter_num_model_change,
            'check_meter_num_model_change_status': vital.check_meter_num_model_change_status,
            'check_meter_num_sz': vital.check_meter_num_sz,
            'check_meter_num_sz_old': vital.check_meter_num_sz_old,
            'check_meter_num_sz_change': vital.check_meter_num_sz_change,
            'check_meter_num_sz_change_status': vital.check_meter_num_sz_change_status,
            'container_version': vital.container_version,
            'container_version_old': vital.container_version_old,
            'cal_date': vital.cal_date,
            'cal_date_old': vital.cal_date_old,
        })

    def delete(self, request, pk):
        """
        删除图书
        路由： DELETE /books/<pk>/
        """
        try:
            vital = VitalData.objects.get(pk=pk)
        except VitalData.DoesNotExist:
            return HttpResponse(status=404)

        vital.delete()

        return HttpResponse(status=204)


class VitalDataViewSet(ModelViewSet):
    queryset = VitalData.objects.all()
    serializer_class = VitalDataSerializer
